# Use a lightweight JDK image
FROM eclipse-temurin:17-jdk

# Set working directory
WORKDIR /app

# Copy only the built jar
COPY target/*.jar app.jar

# Expose the app port (Spring Boot uses 8080 by default)
EXPOSE 8080

# Environment variables (you can override with docker run -e)
ENV EUREKA_PORT=8761
ENV DATASOURCE_PORT=5432
ENV SERVER_PORT=8080

# Start the application
ENTRYPOINT ["sh", "-c", "java -jar app.jar --server.port=${SERVER_PORT}"]
