#!/bin/bash

MAIN_DB_PORT=$1

cockroach sql --insecure --port=${MAIN_DB_PORT} <<EOF

CREATE DATABASE IF NOT EXISTS distributed_exam;
USE distributed_exam;

CREATE TABLE IF NOT EXISTS CANDIDATE (
    CANDIDATE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CANDIDATE_NAME VARCHAR(100) NOT NULL,
    CANDIDATE_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CANDIDATE_PASSWORD VARCHAR(100) NOT NULL,
    COLLEGE VARCHAR(100),
    SKILLS VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ADMIN (
    ADMIN_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ADMIN_NAME VARCHAR(100) NOT NULL,
    ADMIN_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ADMIN_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
    QUESTION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ADMIN_ID UUID NOT NULL REFERENCES ADMIN(ADMIN_ID) ON DELETE CASCADE,
    QUESTION STRING NOT NULL,
    OPTIONS STRING[] NOT NULL,
    ANSWER_INDEX INT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT now()
);

EOF
