-- Table to store user information
CREATE TABLE IF NOT EXISTS CANDIDATE (
    CANDIDATE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CANDIDATE_NAME VARCHAR(100) NOT NULL,
    CANDIDATE_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CANDIDATE_PASSWORD VARCHAR(100) NOT NULL,
    COLLEGE VARCHAR(100),
    SKILLS VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ADMIN (
    ADMIN_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ADMIN_NAME VARCHAR(100) NOT NULL,
    ADMIN_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ADMIN_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
    QUESTION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ADMIN_ID UUID NOT NULL REFERENCES ADMIN(ADMIN_ID) ON DELETE CASCADE,
    QUESTION STRING NOT NULL,
    OPTIONS STRING[] NOT NULL,
    ANSWER_INDEX INT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS TESTS (
    TEST_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ADMIN_ID UUID NOT NULL REFERENCES ADMIN(ADMIN_ID) ON DELETE CASCADE,
    TEST_NAME VARCHAR(255) NOT NULL,
    description TEXT,
    duration INT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS TEST_QUESTIONS (
    TEST_ID UUID REFERENCES tests(TEST_ID) ON DELETE CASCADE,
    QUESTION_ID UUID REFERENCES questions(QUESTION_ID),
    PRIMARY KEY(TEST_ID, QUESTION_ID)
);

CREATE TABLE IF NOT EXISTS CANDIDATE_TESTS (
    TEST_ID UUID REFERENCES tests(TEST_ID) ON DELETE CASCADE,
    CANDIDATE_ID UUID NOT NULL REFERENCES candidate(CANDIDATE_ID) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    score INT NOT NULL,
    PRIMARY KEY (TEST_ID, CANDIDATE_ID)
);

CREATE TABLE IF NOT EXISTS CANDIDATE_RESPONSES (
    TEST_ID UUID REFERENCES tests(TEST_ID) ON DELETE CASCADE,
    CANDIDATE_ID UUID NOT NULL REFERENCES candidate(CANDIDATE_ID) ON DELETE CASCADE,
    QUESTION_ID UUID REFERENCES questions(QUESTION_ID) ON DELETE CASCADE,
    chosen_option INT,
    time_spent BIGINT,
    answer_changed_times INT,
    correct_answer BOOLEAN,
    question_seen BOOLEAN,
    PRIMARY KEY (TEST_ID, CANDIDATE_ID, QUESTION_ID)
);